GET http://localhost:3000/api/resources/getall

GET http://localhost:3000/api/assignments/getall

POST http://localhost:3000/api/resources/add
content-type: application/json

{
    "name": "Abhinav G",
    "location": "onshore",
    "projects": [
        {
            "account": "ABC",
            "assignment": "AAE",
            "rate": 150,
            "role": "Architect",
            "allocation": [
               {
                    "week": "5/9/2018",
                    "hours": "20"
                },
                {
                    "week": "5/30/2018",
                    "hours": "20"
                },
                {
                    "week": "5/16/2018",
                    "hours": "10"
                }
            ]
        },
         {
            "account": "ABC",
            "assignment": "AAD",
            "rate": 150,
            "role": "Architect",
            "allocation": [
               {
                    "week": "5/9/2018",
                    "hours": "20"
                },
                {
                    "week": "5/30/2018",
                    "hours": "20"
                },
                {
                    "week": "5/16/2018",
                    "hours": "10"
                }
            ]
        }
    ]
}

PUT http://localhost:3000/api/resources/updateallocation
content-type: application/json

{
    "id":"5ace3ad431370c218356c3f1",
    "projects":[
        {
            "account": "ABC",
            "assignment": "XYZ",
            "rate": 150,
            "role": "Architect",
            "allocation": [
               {
                    "week": "5/9/2018",k
                    "hours": "20"
                },
                {
                    "week": "5/30/2018",
                    "hours": "20"
                },
                {
                    "week": "5/16/2018",
                    "hours": "10"
                }
            ]
        }
    ]
}



DELETE  http://localhost:3000/api/resources/delete/5ace00203b4b903296621284
